name: Update readme.md

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Install markscribe
        run: |
          export GOPROXY=direct
          go install github.com/mthlpbs/markscribe@8dc7f16
          echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: generate readme
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_URL: ${{ secrets.WAKATIME_URL }}
        run: markscribe -write readme.md templates/readme.md.tpl

      - name: Commit and push if changed
        run: |
          git config user.name "readme-scribe ðŸ¤–"
          git config user.email "actions@github.com"
          git add readme.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update generated README" && git push)